export const Files = {
  bower_comp: '**/bower_components',
  build_dir: '**/build/**',
  change_log: '**/CHANGELOG.md',
  dist_dir: '**/dist',
  eslint_cache: '**/.eslintcache',
  fixtures: '**/__fixtures__',
  git_dir: '**/.git',
  history_dir: '**/.history',
  idea_dir: '**/.idea',
  istanbul_cov: '**/coverage/**',
  js_cov: '**/lib-cov',
  jspm: '**/jspm_packages',
  log_dir: '**/.log',
  logs_dir: '**/logs',
  map_files: '**/*.map',
  min_files: '**/*.min.*',
  mocks: '**/__mocks__',
  next_dir: '**/.next',
  node_modules: '**/node_modules',
  node_repl_history: '**/.node_repl_history',
  npm_cache: '**/.npm',
  npm_debug: '**/npm-debug.log*',
  npm_lock: '**/packages-lock.json',
  nuxt_dir: '**/.nuxt',
  nyc_cov: '**/.nyc_output',
  out_dir: '**/out/**',
  output_dir: '**/.output',
  package_json: 'package.json',
  pnpm_cache: '**/.pnpm',
  pnpm_debug: '**/.pnpm-debug.log*',
  pnpm_lock: '**/pnpm-lock.yaml',
  snapshots: '**/__snapshots__',
  temp_dir: '**/temp/**',
  test_dir: '**/test/**',
  tests_dir: '**/tests/**',
  tests: '**/__tests__',
  tmp_dir: '**/tmp',
  yarn_cache: '**/.yarn',
  yarn_debug: '**/yarn-debug.log*',
  yarn_error: '**/yarn-error.log*',
  yarn_lock: '**/yarn.lock',
}

export const Ext = {
  TS: '.ts',
  TSX: '.tsx',
  DTS: '.d.ts',
  DTSX: '.d.tsx',
  JS: '.js',
  JSON: '.json',
  JSONC: '.jsonc',
  JSON5: '.json5',
  JSX: '.jsx',
  MJS: '.mjs',
  VUE: '.vue',
  YAML: '.yaml',
  YML: '.yml',
}

export const ExtensionGroups = {
  typescript: [Ext.TS, Ext.TSX, Ext.DTS, Ext.DTSX],
  javascript: [Ext.JS, Ext.JSX],
  jsAndTs: [Ext.JS, Ext.JSX, Ext.TS, Ext.TSX, Ext.DTS, Ext.DTSX],
  json: [Ext.JSON, Ext.JSONC, Ext.JSON5],
  vue: [Ext.VUE],
  yml: [Ext.YAML, Ext.YML],
}

export const FileExt = {
  TS: '*.ts',
  TSX: '*.tsx',
  DTS: '*.d.ts',
  DTSX: '*.d.tsx',
  JS: '*.js',
  JSON: '*.json',
  JSONC: '*.jsonc',
  JSON5: '*.json5',
  JSX: '*.jsx',
  MD: '*.md',
  VUE: '*.vue',
  YAML: '*.yaml',
  YML: '*.yml',
}
